FROM openjdk:8-jdk-alpine
MAINTAINER wangchun wangchun@163.com
VOLUME /tmp
ARG JAR_FILE=/project/target/docker-sb-demo-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} /usr/src/myapp/app.jar
WORKDIR /usr/src/myapp/
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","app.jar"]